### ISSUE TITLE
Extra spaces prefixing some error messages

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#14]
I've discovered this issue with more than one error message now. I'd love to understand what causes it.

Two examples are statusSetYellow and invalidArgs as per issue #11

**Comment by fallerOfFalls** [comment]
Also affects errNoPerm

**Comment by RichardB122** [comment]
This simply occurred because when I put the two strings in the code together I forgot there was already a space at the end of the prefix and decided to put an additional space in between them in the code. I removed the space in the code. So now the messages are determined entirely by the prefix (which has a space on the end of it) plus the applicable message.

**Comment by fallerOfFalls** [comment]
Oh right, thanks for the explanation.
