### ISSUE TITLE
Inconsistent formatting between "player has joined the game" and "player has left the game"

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#30]
in "_player_ has joined the game", _player_ is autismchat formatted.
in "_player_ has left the game", _player_ is not autismchat formatted because it's still a vanilla message.

Should "_player_ has left the game" be replaced with an autismchat version?
or should "_player_ has joined the game" be changed so that _player_ is **not** autismchat formatted?

I personally like it being consistent with vanilla, but what colour a player is, is very useful information when they log in. I'm still undecided about what to do about this.

**Comment by fallerOfFalls** [comment]
OK, I've decided, the name shouldn't be AutsmChat formatted.

**Comment by RichardB122** [comment]
Really? It would be just as easy to make the name in the player has left the game message AutismChat formatted as well and while I'm at it I could make the player has left the game message customizable too.

**Comment by fallerOfFalls** [comment]
Nope. I'm sure. Thanks though.

**Comment by RichardB122** [comment]
Alright, so I wasn't sure exactly what you wanted. So I just took my best guess and if it's not right it can always be fixed in the next build.

So the way it now works is that if the player is in your party when they join their name is colored, but if they are not in your party (i.e it's the vanilla message) then their name is not colored.

**Comment by fallerOfFalls** [comment]
I meant for they name _never_ to be autismchat formatted, so it's always yellow, even when they are in your party.

Yeah, it's okay. fix in next build.
