### ISSUE TITLE
username changes not reflected in messages

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#39]
someone changed their username. I joined them using their new username, and it said that I'd joined the party _oldusername_.

**Comment by RichardB122** [comment]
This issue should be fixed in build 34. You will have to reset your data in order for it to work though. Basically there is not an easy way to retrieve a user's name when they are offline based on a uuid so I store a list of uuids and their username in the data folder. It used to work so that the first time a new user logged in it set their uuid and username and never did anything again, but I changed it so now it checks if their username has changed every time they login and updates it if it has.

This does mean however that you will have to login after you have renamed your account for it to take effect and update your name on the server.

**Comment by fallerOfFalls** [comment]
Thanks!
I'm not going to be able to test this fix any time soon so I'll just close the issue and then reopen it if it comes up again.
